### ISSUE TITLE
Bot creation doesn't fail with other "Supported account types" options selected

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1432]
[This section](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0&source=docs#i-need-to-manually-create-my-app-registration-how-do-i-create-my-own-app-registration) appears to be wrong:

> > [!IMPORTANT]
> > In the *Supported account types*, select the *Accounts in any organizational directory and personal Microsoft accounts (e.g. Skype, Xbox, Outlook.com)* radio button. If any of the other options are selected, **bot creation will fail**.
> 
> ![registration details](https://docs.microsoft.com/en-us/azure/bot-service/media/app-registration/registration-details.png)

I have successfully created a bot channels registration using an app registration with `AzureADMyOrg` as the sign-in audience. I presume the sign-in audience field is ignored by the bot service, since I've only seen it used for AAD OAuth connection app registrations and not bot app registrations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 253d4e99-7fc5-cc8d-5b07-29bf2d78687a
* Version Independent ID: cdc0528d-cf1a-e015-1d8a-31ed062648f8
* Content: [Bot Service Frequently Asked Questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0&source=docs#app-registration)
* Content Source: [articles/bot-service-resources-bot-framework-faq.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-resources-bot-framework-faq.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **kamrani**

**Comment by aosolis** [comment]
@v-kydela When you select the single-tenant option ("Accounts in this organizational directory only") does your bot *work*? We tried this earlier and the bot is not able to get an access token to talk to the APIs, because the single-tenant AAD app cannot get tokens in the `botframework.com` tenant.

**Comment by v-kydela** [comment]
The will receive messages just fine, but when the bot tries to send messages I get this error:

```
Failed to acquire token for client credentials. (AADSTS700016: Application with identifier '9660950d-27a3-4a78-9c22-188df9c85221' was not found in the directory 'botframework.com'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: b3d66e5b-f1dc-49f0-9195-79fc0a436e00
Correlation ID: dbafe579-8b00-4fff-912b-9c6d292f2e19
Timestamp: 2019-11-26 21:39:20Z) (AADSTS700016: Application with identifier '9660950d-27a3-4a78-9c22-188df9c85221' was not found in the directory 'botframework.com'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: cae2e190-ec48-438f-a952-d3af0c909a00
Correlation ID: 0806b917-f8ab-4991-8156-c19bbf7f5431
Timestamp: 2019-11-26 21:39:20Z) (AADSTS700016: Application with identifier '9660950d-27a3-4a78-9c22-188df9c85221' was not found in the directory 'botframework.com'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: 50f27dfa-e436-4dab-82d9-684e4b075d00
Correlation ID: a3e10eeb-21ed-484e-b9b0-8c20188122d3
Timestamp: 2019-11-26 21:39:20Z) (AADSTS700016: Application with identifier '9660950d-27a3-4a78-9c22-188df9c85221' was not found in the directory 'botframework.com'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: 704eaf10-82f9-4992-9e1f-d3eb65df5600
Correlation ID: e0d25168-204c-45df-bf7b-18eecc8c65be
Timestamp: 2019-11-26 21:39:20Z) (AADSTS700016: Application with identifier '9660950d-27a3-4a78-9c22-188df9c85221' was not found in the directory 'botframework.com'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: abce8e18-9088-4155-bd67-07f1810a7100
Correlation ID: 374cd3bd-0cf3-4616-a578-ba5d0ac3b257
Timestamp: 2019-11-26 21:39:21Z) (AADSTS700016: Application with identifier '9660950d-27a3-4a78-9c22-188df9c85221' was not found in the directory 'botframework.com'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: 691fdffb-2526-46d0-b4f1-f4144cc07500
Correlation ID: 5b6d2ede-98a9-425b-87dc-5cdace3cf6a3
Timestamp: 2019-11-26 21:39:21Z) (AADSTS700016: Application with identifier '9660950d-27a3-4a78-9c22-188df9c85221' was not found in the directory 'botframework.com'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: 58aaae5a-e43e-4559-8ca6-42da0af29500
Correlation ID: 5bce40a2-2269-424e-9c14-3aeab4688b31
Timestamp: 2019-11-26 21:39:21Z) (AADSTS700016: Application with identifier '9660950d-27a3-4a78-9c22-188df9c85221' was not found in the directory 'botframework.com'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: cae2e190-ec48-438f-a952-d3af4c909a00
Correlation ID: f6248df8-d0dc-4e1a-98f8-0b5d6e11b413
Timestamp: 2019-11-26 21:39:21Z) (AADSTS700016: Application with identifier '9660950d-27a3-4a78-9c22-188df9c85221' was not found in the directory 'botframework.com'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: 704eaf10-82f9-4992-9e1f-d3eb9ddf5600
Correlation ID: 1b7a5da7-1b26-48fe-b4a3-8c02dbe84ba3
Timestamp: 2019-11-26 21:39:22Z) (AADSTS700016: Application with identifier '9660950d-27a3-4a78-9c22-188df9c85221' was not found in the directory 'botframework.com'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: 50f27dfa-e436-4dab-82d9-684e96075d00
Correlation ID: 33af82af-f66c-49ed-bd73-ffb7ca085c1b
Timestamp: 2019-11-26 21:39:22Z) (AADSTS700016: Application with identifier '9660950d-27a3-4a78-9c22-188df9c85221' was not found in the directory 'botframework.com'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: 74e1ad83-7890-4501-99f6-4cb4936b5a00
Correlation ID: a6d589e5-daf4-42cc-8075-086fc12536df
Timestamp: 2019-11-26 21:39:22Z)
   at Microsoft.Bot.Connector.Authentication.Retry.<Run>d__0`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.Authentication.AdalAuthenticator.<GetTokenAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.Authentication.AppCredentials.<GetTokenAsync>d__32.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.Authentication.AppCredentials.<ProcessHttpRequestAsync>d__31.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.Conversations.<ReplyToActivityWithHttpMessagesAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.ConversationsExtensions.<ReplyToActivityAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Bot.Builder.BotFrameworkAdapter.<SendActivitiesAsync>d__28.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass22_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.TurnContext.<SendActivityAsync>d__21.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.TextPrompt.<OnPromptAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Prompt`1.<BeginDialogAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.<BeginDialogAsync>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.<PromptAsync>d__23.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CoreBot1.Dialogs.MainDialog.<IntroStepAsync>d__3.MoveNext() in C:\Dev\CSharp\CoreBot1\CoreBot1\Dialogs\MainDialog.cs:line 59
```

Perhaps we should say the bot will be unusable instead of saying bot creation will fail.

**Comment by WashingtonKayaker** [comment]
Updated the Important message from:

If any of the other options are selected, **bot creation will fail**.

To:

If any of the other options are selected, **the bot will be unusable**.
