### ISSUE TITLE
Got 502 Bad Gateway Error while sending request to https://smba.trafficmanager.net/amer

### ISSUE THREAD

**Issue by MarkLeiSource** [MicrosoftDocs/bot-docs#1464]
I'm developing a bot app for MS Teams platform , and sometimes when my service sending the reply to the teams user, I got 502 Bad Gateway Error from https://smba.trafficmanager.net/amer, here is the error stacks:
Error: POST to 'https://smba.trafficmanager.net/amer/v3/conversations/*****/activities/*****' failed: [502] Bad Gateway
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:675:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Is there any server down behind the traffic manager of " https://smba.trafficmanager.net/amer " ?

**Comment by dmvtech** [comment]
We are looking into this to see if there were any issues with that resource. Stand by.

Are you still exhibiting problems currently?

**Comment by MarkLeiSource** [comment]
The error seems can not be reproduced these days. Also I add some backoff retry logic，just in case.

**Comment by dmvtech** [comment]
Ok, thank you. My assumption is that it was likely some transient issue, and might have been with the hops between the client and server. Please let us know if this issue reoccurs for you.

**Comment by cbuffevant** [comment]
@dmvtech I'm getting a similar error for a Teams Bot (v3).
```
Error: POST to 'https://smba.trafficmanager.net/amer/v3/conversations/******/activities' failed: [502] Bad Gateway
```

Stack trace:
```
at Request._callback (/usr/src/node_modules/botbuilder/lib/bots/ChatConnector.js line 545 col 46)
callback(new Error(txt), response, null);
at Request.self.callback (/usr/src/node_modules/request/request.js line 186 col 22)
self._callback.apply(self, arguments)
at Request.emit (events.js line 198 col 13)
at Request.<anonymous> (/usr/src/node_modules/request/request.js line 1163 col 10)
self.emit('complete', response, response.body)
at Request.emit (events.js line 198 col 13)
at IncomingMessage.<anonymous> (/usr/src/node_modules/request/request.js line 1085 col 12)
self.emit('end', chunk)
at Object.onceWrapper (events.js line 286 col 20)
at IncomingMessage.emit (events.js line 203 col 15)
at endReadableNT (_stream_readable.js line 1145 col 12)
at process._tickCallback (internal/process/next_tick.js line 63 col 19)
```

Do you have any idea what's going on?

**Comment by agxs** [comment]
I've been getting these a lot today too.

**Comment by cbuffevant** [comment]
It seems my bot works beside these errors... so, not entirely sure whether be worry or not...

**Comment by agxs** [comment]
Hmm mine hasn't been sending messages, but maybe it's unrelated then. Thanks for the info.

**Comment by oariel** [comment]
I'm getting these errors on EMEA. This started on March 16th (same day as the Teams outage in EMEA). Americas is fine. Error is consistent but sometimes the call completes ok, and sometimes it doesn't. Anyone experiencing similar issues? 

Error: POST to 'https://smba.trafficmanager.net/emea/v3/conversations/XXXXXXXXXX/activities/XXXXXXXXXXX' failed: [502] Bad Gateway

**Comment by agxs** [comment]
That's interesting, me too since around that day as well. I've never had a working message sent since then.

**Comment by oariel** [comment]
> That's interesting, me too since around that day as well. I've never had a working message sent since then.

Good to know I'm not alone..  Looking at the logs, sometime I also get "[412] Precondition Failed" errors as well. I've tried to report this to Microsoft but they keep redirecting me to the O365 support line. If anyone can point me in the right direction I'll really appreciate it since for the last week+ our EMEA users are able to use our app.

**Comment by dmvtech** [comment]
API outage: Bots posting typing indicators may receive 502s

https://developer.microsoft.com/en-us/microsoft-teams/blogs/outage-bots-posting-typing-indicators-will-receive-502s/

**Comment by agxs** [comment]
Due to the recent changes MS made to change the response from typing indicators from 50x to 202 my bot is working again!
