### ISSUE TITLE
More random "Error: Authorization has been denied for this request" problems

### ISSUE THREAD

**Issue by dupuis2387** [MicrosoftDocs/bot-docs#1548]
i'm using the **nodejs version of "botbuilder": "~4.5.1"** 
and I'm still encountering issues with "Error: Authorization has been denied for this request" even after having 
`MicrosoftAppCredentials.trustServiceUrl('https://smba.trafficmanager.net/apis/', new Date(8640000000000000));` 
in my code. 

It randomly happens and without doing anything, it'll resume being able to communicate with the person that I've \<SNIP\>'d out. 

FWIW, this bot is hosted in Azure under an app service instance, and has "Always On" already on.
If a timestamp would help troubleshoot if there was a fluke with some service bot/skype outage, it just happened on  Mon 2/3/2020 3:59 PM EST

```
{
   "stack": "Error: Authorization has been denied for this request.\n    at new RestError (D:\\home\\site\\wwwroot\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:1397:28)\n    at D:\\home\\site\\wwwroot\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:1849:37\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
   "message": "Authorization has been denied for this request.",
   "statusCode": 401,
   "request": {
      "body": {
         "type": "message",
         "serviceUrl": "https://smba.trafficmanager.net/apis/",
         "channelId": "skype",
         "from": {
            "id": "<SNIP>",
            "name": "<SNIP>"
         },
         "conversation": {
            "id": "<SNIP>"
         },
         "recipient": {
            "id": "<SNIP>",
            "name": "<SNIP>"
         },
         "text": "The message that the bot was trying to send to the recipient.",
         "inputHint": "acceptingInput",
         "replyToId": "<SNIP>"
      }
   },
   "response": {
      "body": {
         "message": "Authorization has been denied for this request."
      }
   },
   "body": {
      "message": "Authorization has been denied for this request."
   }
}
```

**Comment by mdrichardson** [comment]
@dupuis2387 Can you provide a conversation ID that this has occurred on? At the very least, I'll need an AppId or bot name to look into this further.

Where in your code are you calling `trustServiceUrl()`? So long as it's called prior to the bot sending a message to that serviceUrl (even after a bot restart), it should be fine.

**Comment by dupuis2387** [comment]
sure...here we are (i thought divulging that would be sensitive information):

```
{
   "stack": "Error: Authorization has been denied for this request.\n    at new RestError (D:\\home\\site\\wwwroot\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:1397:28)\n    at D:\\home\\site\\wwwroot\\node_modules\\@azure\\ms-rest-js\\dist\\msRest.node.js:1849:37\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
   "message": "Authorization has been denied for this request.",
   "statusCode": 401,
   "request": {
      "body": {
         "type": "message",
         "serviceUrl": "https://smba.trafficmanager.net/apis/",
         "channelId": "skype",
         "from": {
            "id": "28:e7e117fc-904e-4782-af12-dceafb4e9ac0",
            "name": "NRS VIDEO RELAY SERVICE"
         },
         "conversation": {
            "id": "29:1zNwNjv0VsMmllDwoj8tbyE_c_9JawLJZtToLNeskZeJ5z8swuX0MDZIBu9X8Ok-b"
         },
         "recipient": {
            "id": "29:1zNwNjv0VsMmllDwoj8tbyE_c_9JawLJZtToLNeskZeJ5z8swuX0MDZIBu9X8Ok-b",
            "name": "NRS VRSTERP10"
         },
         "text": "<SNIP>",
         "inputHint": "acceptingInput",
         "replyToId": "1580763518872"
      }
   },
   "response": {
      "body": {
         "message": "Authorization has been denied for this request."
      }
   },
   "body": {
      "message": "Authorization has been denied for this request."
   }
} 

```

**Comment by mdrichardson** [comment]
@dupuis2387 I'll start looking into this. As far as sensitive info, the bot name or appId is fine--it's just passwords, mostly that you need to keep private.

Placement is fine. Are you sure that's the right serviceUrl for every message? I don't recall what Skype does, but Teams has several different serviceUrls.

**Comment by dupuis2387** [comment]
@mdrichardson so per the provided Microsoft samples, to continue a conversation, we're meant to keep a json payload from a conversation interaction that looks like 
```

{
    "activityId": "1572800137595",
    "bot": {
        "id": "28:e7e117fc-904e-4782-af12-dceafb4e9ac0",
        "name": "NRS VIDEO RELAY SERVICE"
    },
    "channelId": "skype",
    "conversation": {
        "id": "29:1qM0tG1lMQtJQAGw1E4iR9KpzvSnYbiA1w2HkIctUBBM"
    },
    "serviceUrl": "https://smba.trafficmanager.net/apis/",
    "user": {
        "id": "29:1qM0tG1lMQtJQAGw1E4iR9KpzvSnYbiA1w2HkIctUBBM",
        "name": "Alex"
    }
}

```
Every instance of every contact that we've accrued and saved the payload thereof, has only every had the above service url. And all we care about is just communication on the skype channel (not skype for business, teams, or really anything else). 

However, i do not definitively know; i dont know of any place that lists all serviceUrls you're meant to trust in regards to skype.....but given that the error recorded in my original post, has `https://smba.trafficmanager.net/apis/` as the api url, im imagining that *that* rules out other potential serviceUrls not being trusted, but I could be wrong.

**Comment by mdrichardson** [comment]
The best way to ensure this works, even if an API is changed, is right before the bot sends a message to the user, call `trustServiceUrl(turnContext.activity.serviceUrl, <expiration>)`. Again, still looking into the specifics, though.

**Comment by mdrichardson** [comment]
@dupuis2387 I forgot that we can't check Skype bots via ConversationId. Can you provide the bot's name (the name of the App Registration in Azure)?

**Comment by dupuis2387** [comment]
the display name of the bot? "NRS VIDEO RELAY SERVICE" here's the direct skype contact link https://join.skype.com/bot/e7e117fc-904e-4782-af12-dceafb4e9ac0

**Comment by mdrichardson** [comment]
@dupuis2387 I'm not able to find it by that name on the backed. What is it listed as in [App Registrations](https://ms.portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade)? If it's the same, what is it listed in the Web App Bot or Bot Channels Registration in the Azure Portal?

**Comment by dupuis2387** [comment]
The bot channels registration is **CnxNrsAlphaDeployment**

**Comment by mdrichardson** [comment]
@dupuis2387 Got it. Any chance your bot has >100 users?

**Comment by dupuis2387** [comment]
Yes, since it "went live", there's been a total of 371  individual people that have communicated with it

**Comment by mdrichardson** [comment]
@dupuis2387 That's likely your problem. If you open your Web App Bot/Bot Channels Registration in the Azure Portal, click Channels, then click "edit" by Skype:

![image](https://user-images.githubusercontent.com/40401643/73885239-45780880-481c-11ea-9c3d-00f93f225749.png)

If you haven't re-published it recently, you might be okay. I'm currently not seeing any issues on the backend, though -- Skype handles most of the communication, so there's not a _ton_ that we can look into.

**Comment by dupuis2387** [comment]
Yep, so I got it in before the deadline , and it was approved, literally the day of, in October,  as confirmed by a Microsoft support engineer. Also, I've not republished since. Anything else it could be?

**Comment by mdrichardson** [comment]
@dupuis2387 I see.

1. Is this an intermittent problem, still, or was it only really happening on Monday?
2. If still occuring can you try adding `trustServiceUrl(turnContext.activity.serviceUrl, <expiration>)` at the top of `onMessage()` and let me know if the problem still occurs?

**Comment by dupuis2387** [comment]
It's been happening on and off probably since it went live in October. I have recorded instances on 12/4, 1/3, 1/10, and 1/16, all across different contacts/activities. But, let me go ahead and try your suggested code change, and see if it persists.  Thank you, for looking at this.

**Comment by mdrichardson** [comment]
@dupuis2387 Sounds good. Did you change your Bot ID recently? I can't seem to find any logs on our end older than a couple of days. Might be a Skype thing, though, now that it's deprecated.

**Comment by mdrichardson** [comment]
@dupuis2387 How's this going?

**Comment by dupuis2387** [comment]
The code change went into production 48hrs ago. However, I can't say it's 100% fixed the issue yet, given how random it is, when it pops up. 
Should I close for now and re-open it again, later, if it re-manifests?

**Comment by mdrichardson** [comment]
@dupuis2387 We can close for now. If it pops up again, please get timestamps as accurate as possible along with any logs you can share.

**Comment by praveenkumar197** [comment]
I am getting the error while trying to send the message without an trigger from the user in teams by using the cron scheduler(node package) but sometimes it throwing the error,
**(node:1) UnhandledPromiseRejectionWarning: Error: Authorization has been denied for this request.** 
without changing or restarting the code it getting solved but after sometimes the same issues is arising can anyone help me to come out of it.
