### ISSUE TITLE
Getting issue while enabling direct line app service extension in azure bot service

### ISSUE THREAD

**Issue by gourav-madan** [MicrosoftDocs/bot-docs#1965]
I have followed the exact steps mentioned in below Microsoft link:

https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0

**Still the value of ib and ob are coming false:
{"v":"1.0.0.0.55fa54091a1e3b168628d4000ee2b06a88bbc2ac","k":true,"ib":false,"ob":false,"initialized":true}**

 Bot in webchat stops working after adding <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel> setting in .csproj file.
<img width="535" alt="webchaterror" src="https://user-images.githubusercontent.com/57317108/101500558-a4566300-3994-11eb-94b5-87b0f6978157.PNG">

**Also am not able to generate token from the below link:
https://[my bot name here].azurewebsites.net/.bot/v3/directline/tokens/generate**

_I had replicate the same config on two bots but no luck. Please help me on this its urgent.
I have attached my changes, please let me know where i'm getting wrong or is this the issue with Microsoft._

<img width="551" alt="apllication settings" src="https://user-images.githubusercontent.com/57317108/101499983-e632d980-3993-11eb-865e-cb5196ff7420.PNG">
<img width="628" alt="ib and on values" src="https://user-images.githubusercontent.com/57317108/101499991-e7fc9d00-3993-11eb-9d4e-2f0fd5ee23c3.PNG">
<img width="917" alt="namedpipe" src="https://user-images.githubusercontent.com/57317108/101499994-e8953380-3993-11eb-9d68-0d420de3f094.PNG">
<img width="639" alt="outofprocess" src="https://user-images.githubusercontent.com/57317108/101500004-e92dca00-3993-11eb-8097-47bf847d70f7.PNG">
<img width="377" alt="web socket config" src="https://user-images.githubusercontent.com/57317108/101500015-e9c66080-3993-11eb-8336-8086336d99fd.PNG">

**Comment by mmiele** [comment]
@gourav-madan  

ib determines whether Direct Line ASE can establish an inbound connection with the bot.
ob determines whether Direct Line ASE can establish an outbound connection with the bot.

If both are false, it means that Direct Line cannot establish the connection with your bot. 

Do these steps:
1. Check that you can talk to your bot via the Emulator. You can find related information at this location: [Debug with the Emulator](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-emulator?view=azure-bot-service-4.0&tabs=csharp). 
1. If you have deployed your bot, for example in Azure, test it using Web Chat
1. For the token generation look at code samples at this location [Code examples](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0#code-examples),

**Comment by gourav-madan** [comment]
@mmiele I have tried debugging it & error is coming in UseNamedPipes middleware and found below exception:

**I am using latest virtual assistant template:**
https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/assistants/virtual-assistant

![image](https://user-images.githubusercontent.com/57317108/101886671-ba7e4200-3b93-11eb-9a22-e4c653f7d0da.png)

![image](https://user-images.githubusercontent.com/57317108/101886584-9d497380-3b93-11eb-8dc0-3594d40ecec5.png)

Stack Trace
at Microsoft.Bot.Builder.Integration.AspNet.Core.ApplicationBuilderExtensions.UseNamedPipes(IApplicationBuilder applicationBuilder, String pipeName)
   at VirtualAssistantSample.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Users\Taruna.Soni\Desktop\virtual-assistant\VirtualAssistantSample\Startup.cs:line 171
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__31.MoveNext()

**Comment by gourav-madan** [comment]
Is there any update on this?

**Comment by mmiele** [comment]
@gourav-madan 
So far I found out that the VA template does not support Direct Line App Service Extension (DL-ASE).
To make it work, the VA template with DL-ASE requires a lot of customization, so it is not provided out of the box. 
You might want to pose the question on [StackOverflow](https://stackoverflow.com/search?q=%5Bbotframework%5D+virtual+assistant&s=b3c3b1b9-01aa-411a-b011-6cd4321f0767) also.

**Comment by thomasgauvin** [comment]
@gourav-madan I had the same issue in the NodeJS tutorial. I was able to resolve this by importing the BotFrameworkAdapter instead of the CloudAdapter. Note that I'm working in NodeJS rather than C#, but perhaps there is a similar solution.

![image](https://user-images.githubusercontent.com/35609369/143913508-6e055cce-a3a1-49d9-b8c7-6ddff5513298.png)
