### ISSUE TITLE
Including the asyncio dependency from the Python bot creation tutorial causes deployment issues

### ISSUE THREAD

**Issue by kimadeline** [MicrosoftDocs/bot-docs#2073]
**Describe the bug**

Hello! 

I was following the tutorials to [create a basic Python bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-create-basic-bot?view=azure-bot-service-4.0&tabs=python%2Cvs) and then [deploy it to Azure](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-deploy-basic-bot?view=azure-bot-service-4.0&tabs=python), and having `asyncio` in my `requirements.txt` led the bot to not work once deployed. 

The tutorial [prerequisites](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-create-basic-bot?view=azure-bot-service-4.0&tabs=python%2Cvs#prerequisites) suggest Python 3.6, 3.7 or 3.8, however when I was testing it Oryx uses 3.7.9.

I was following the tutorial using Python 3.7, which comes with its own version of `asyncio`. Including it in the `requirements.txt` file caused `asyncio==3.4.3` to be downloaded, and I could not interact with the not using Web Chat afterwards.

**To Reproduce**
1. Use Python 3.7
2. Create a bot following the [Templates](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-create-basic-bot?view=azure-bot-service-4.0&tabs=python%2Cvs#templates) and [Create a Bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-create-basic-bot?view=azure-bot-service-4.0&tabs=python%2Cvs#create-a-bot) sections of the bot creation tutorial
2. Follow the deployment steps of the deployment tutorial, [with a new resource group](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-deploy-basic-bot?view=azure-bot-service-4.0&tabs=python#deploy-via-arm-template-with-new-resource-group)
2. Deploy the bot and wait for the deployment command to succeed
3. Go to the Azure Portal, and try to test the bot via Web Chat
4. The bot doesn't display its welcome message

**Expected behavior**

For the bot to display its welcome message, and being able to interact with it.

**Screenshots**

This is what I could see when going to the "Channels" section and clicking on the warnings:

![image](https://user-images.githubusercontent.com/51720070/117508100-dddbcc00-af3c-11eb-8f33-2d38e0a730c9.png)

**Additional context**

<details>

<summary>Logs</summary>

<p>

```
2021-04-26T00:15:50.956208163Z 
2021-04-26T00:15:50.956239564Z   _____                               
2021-04-26T00:15:50.956244964Z   /  _  \ __________ _________   ____  
2021-04-26T00:15:50.956248964Z  /  /_\  \___   /  |  \_  __ \_/ __ \ 
2021-04-26T00:15:50.956253064Z /    |    \/    /|  |  /|  | \/\  ___/ 
2021-04-26T00:15:50.956257064Z \____|__  /_____ \____/ |__|    \___  >
2021-04-26T00:15:50.956261164Z         \/      \/                  \/ 
2021-04-26T00:15:50.956265064Z 
2021-04-26T00:15:50.956268664Z A P P   S E R V I C E   O N   L I N U X
2021-04-26T00:15:50.956272564Z 
2021-04-26T00:15:50.956276164Z Documentation: http://aka.ms/webapp-linux
2021-04-26T00:15:50.956279764Z Python 3.7.9
2021-04-26T00:15:50.956283364Z Note: Any data outside '/home' is not persisted
2021-04-26T00:15:51.897668513Z Starting OpenBSD Secure Shell server: sshd.
2021-04-26T00:15:51.965534589Z Site's appCommandLine: gunicorn --bind 0.0.0.0 --worker-class aiohttp.worker.GunicornWebWorker --timeout 600 app:APP
2021-04-26T00:15:51.966501592Z Launching oryx with: create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -virtualEnvName antenv -defaultApp /opt/defaultsite -bindPort 8000 -userStartupCommand 'gunicorn --bind 0.0.0.0 --worker-class aiohttp.worker.GunicornWebWorker --timeout 600 app:APP'
2021-04-26T00:15:52.368553240Z Found build manifest file at '/home/site/wwwroot/oryx-manifest.toml'. Deserializing it...
2021-04-26T00:15:52.395748411Z Build Operation ID: |KtkTWfnd4Qw=.cf65601c_
2021-04-26T00:15:52.397794516Z Oryx Version: 0.2.20210225.2, Commit: f7b557f29a83aa078cc94c0056e7337c07f14271, ReleaseTagName: 20210225.2
2021-04-26T00:15:52.403554031Z Output is compressed. Extracting it...
2021-04-26T00:15:52.415595062Z Extracting '/home/site/wwwroot/output.tar.gz' to directory '/tmp/8d90788364599f5'...
2021-04-26T00:15:55.823179375Z App path is set to '/tmp/8d90788364599f5'
2021-04-26T00:15:57.900692238Z Writing output script to '/opt/startup/startup.sh'
2021-04-26T00:15:58.787021287Z Using packages from virtual environment antenv located at /tmp/8d90788364599f5/antenv.
2021-04-26T00:15:58.787690689Z Updated PYTHONPATH to ':/tmp/8d90788364599f5/antenv/lib/python3.7/site-packages'
2021-04-26T00:16:05.371942081Z 
2021-04-26T00:16:05.371967781Z Error: class uri 'aiohttp.worker.GunicornWebWorker' invalid or not found: 
2021-04-26T00:16:05.371973981Z 
2021-04-26T00:16:05.371984281Z [Traceback (most recent call last):
2021-04-26T00:16:05.371989281Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/gunicorn/util.py", line 99, in load_class
2021-04-26T00:16:05.371993881Z     mod = importlib.import_module('.'.join(components))
2021-04-26T00:16:05.371998381Z   File "/opt/python/3.7.9/lib/python3.7/importlib/__init__.py", line 127, in import_module
2021-04-26T00:16:05.372003082Z     return _bootstrap._gcd_import(name[level:], package, level)
2021-04-26T00:16:05.372017982Z   File "", line 1006, in _gcd_import
2021-04-26T00:16:05.372022682Z   File "", line 983, in _find_and_load
2021-04-26T00:16:05.372026782Z   File "", line 953, in _find_and_load_unlocked
2021-04-26T00:16:05.372030782Z   File "", line 219, in _call_with_frames_removed
2021-04-26T00:16:05.372034782Z   File "", line 1006, in _gcd_import
2021-04-26T00:16:05.372038782Z   File "", line 983, in _find_and_load
2021-04-26T00:16:05.372042682Z   File "", line 967, in _find_and_load_unlocked
2021-04-26T00:16:05.372046682Z   File "", line 677, in _load_unlocked
2021-04-26T00:16:05.372050582Z   File "", line 728, in exec_module
2021-04-26T00:16:05.372054682Z   File "", line 219, in _call_with_frames_removed
2021-04-26T00:16:05.372058582Z   File "/tmp/8d90788364599f5/antenv/lib/python3.7/site-packages/aiohttp/__init__.py", line 6, in 
2021-04-26T00:16:05.372062782Z     from .client import BaseConnector as BaseConnector
2021-04-26T00:16:05.372066482Z   File "/tmp/8d90788364599f5/antenv/lib/python3.7/site-packages/aiohttp/client.py", line 3, in 
2021-04-26T00:16:05.372070782Z     import asyncio
2021-04-26T00:16:05.372074482Z   File "/tmp/8d90788364599f5/antenv/lib/python3.7/site-packages/asyncio/__init__.py", line 21, in 
2021-04-26T00:16:05.372078582Z     from .base_events import *
2021-04-26T00:16:05.372082282Z   File "/tmp/8d90788364599f5/antenv/lib/python3.7/site-packages/asyncio/base_events.py", line 296
2021-04-26T00:16:05.372086282Z     future = tasks.async(future, loop=self)
2021-04-26T00:16:05.372089982Z                        ^
2021-04-26T00:16:05.372093682Z SyntaxError: invalid syntax
2021-04-26T00:16:05.372097482Z ]
2021-04-26T00:16:05.372101082Z 
```

</p>
</details>

**Comment by emgrol** [comment]
@kimadeline It seems like this may be a deployment issue, possibly related to Oryx. I've added the support label so you should be getting help soon.

**Comment by kimadeline** [comment]
Hi @emgrol, thank you for getting back to me!

My issue was that creating a bot using Python 3.7 would fail when following the [template](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-create-basic-bot?view=azure-bot-service-4.0&tabs=python%2Cvs#templates) shown in the docs as-is:

![image](https://user-images.githubusercontent.com/51720070/122620290-6aeb6800-d047-11eb-9769-c97744fc5426.png)

From Python 3.7 onwards `asyncio` is already included in Python, and explicitly listing it in the requirements.txt provided in the [BotBuilder-Samples templates](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/python/01.console-echo/requirements.txt) caused me some deployment issues.

I fixed my issue by removing the `asyncio` from my `requirements.txt` file (as such, I don't require immediate support), however I couldn't find any mention of that in the docs.

Let me know if there's anything else I should clarify!

**Comment by dmvtech** [comment]
I wasn't able to reproduce the issue. Are you doing `pip install` before deploying? You shouldn't.
