### ISSUE TITLE
PUT to https://smba.trafficmanager.net/amer/v3/conversations/ failed with [405] Method Not Allowed

### ISSUE THREAD

**Issue by aniproof** [MicrosoftDocs/bot-docs#2142]
We are using bot builder to send messages and after user's action we need to update the card. 
This call to update the card fails
```
    session.connector.update(msg.toMessage(), (err) => {
          //logging here
   })
```
Here is the error: 
message: PUT to 'https://smba.trafficmanager.net/amer/v3/conversations/{someID}/activities' failed: [405] Method Not Allowed

stack: 
Error: PUT to 'https://smba.trafficmanager.net/amer/v3/conversations/{someID}/activities' failed: [405] Method Not Allowed
    at Request._callback (/usr/src/app/node_modules/botbuilder/lib/bots/ChatConnector.js:722:46)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at /usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19
    at Scope._activate (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/async_resource.js:47:14)
    at Scope.activate (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)

Here are the botbuilder versions that we use:

    "botbuilder": "^3.30.0",
    "botbuilder-teams": "^0.2.9",

**To Reproduce**
1. Successfully creating a card 
2. Call session.connector.update
3. See the error 405 not allowed

**Expected behavior**
To update the card without error

**Comment by dmvtech** [comment]
Hi @aniproof Can you confirm that this is still reproducible at this time?

**Comment by dmvtech** [comment]
Closing due to lack of response.
