### ISSUE TITLE
Azure Bot skill -  Operation returned an invalid status code 'NotFound'

### ISSUE THREAD

**Issue by ShilpaSharePoint** [MicrosoftDocs/bot-docs#2197]
Hi,

I downloaded the sample - skills-sso-cloudadapter from below link. 
https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/82.skills-sso-cloudadapter

Followed the steps described to configure required settings for azure bot & OAuth connection. Deployed both rootbot and skillbot on Azure.
Parent bot works fine, but invoking skill gives error has below:  Operation returned an invalid status code 'NotFound' at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.CloudAdapterBase.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at Microsoft.BotBuilderSamples.SkillBot.SsoSkillAdapterWithErrorHandler.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken) in \skills-sso-cloudadapter\SkillBot\SsoSkillAdapterWithErrorHandler.cs:line 53
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.ChoicePrompt.OnPromptAsync(ITurnContext turnContext, IDictionary`2 state, PromptOptions options, Boolean isRetry, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Prompt`1.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.PromptAsync(String dialogId, PromptOptions options, CancellationToken cancellationToken)
   at Microsoft.BotBuilderSamples.SkillBot.Dialogs.SsoSkillDialog.PromptActionStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken) in \skills-sso-cloudadapter\SkillBot\Dialogs\SsoSkillDialog.cs:line 57
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.OnStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.RunStepAsync(DialogContext dc, Int32 index, DialogReason reason, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.ComponentDialog.BeginDialogAsync(DialogContext outerDc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.BotBuilderSamples.SkillBot.Dialogs.ActivityRouterDialog.ProcessActivityAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken) in \skills-sso-cloudadapter\SkillBot\Dialogs\ActivityRouterDialog.cs:line 43
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.OnStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.RunStepAsync(DialogContext dc, Int32 index, DialogReason reason, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.ComponentDialog.BeginDialogAsync(DialogContext outerDc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.InnerRunAsync(ITurnContext turnContext, String dialogId, DialogContext dialogContext, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.InternalRunAsync(ITurnContext turnContext, String dialogId, DialogContext dialogContext, DialogStateManagerConfiguration stateConfiguration, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.InternalRunAsync(ITurnContext turnContext, String dialogId, DialogContext dialogContext, DialogStateManagerConfiguration stateConfiguration, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.RunAsync(Dialog dialog, ITurnContext turnContext, IStatePropertyAccessor`1 accessor, CancellationToken cancellationToken)
   at Microsoft.BotBuilderSamples.SkillBot.Bots.SkillBot`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in \skills-sso-cloudadapter\SkillBot\Bots\SkillBot.cs:line 33
   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) -- Microsoft.Bot.Connector
Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'NotFound'
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.CloudAdapterBase.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at .SkillBot.SsoSkillAdapterWithErrorHandler.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken) in \skills-sso-cloudadapter\SkillBot\SsoSkillAdapterWithErrorHandler.cs:line 53
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()

2. As per the instructions if i leave the MicrosoftAppType and MicrosoftAppTenantId empty, then it does not invoke parent bot, error as below:

 unhandled error : Failed to acquire token for client credentials. (-----------: Application with identifier '-----------' was not found in the directory 'Bot Framework'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

Correlation ID: ------------------
)
System.AggregateException: Failed to acquire token for client credentials. (-------------: Application with identifier '---------------' was not found in the directory 'Bot Framework'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94555e05-7272-f072-a697-dbcf95afe256
* Version Independent ID: 23411b2c-7844-4ba2-01e7-4dcaa4827802
* Content: [Implement a skill consumer - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/skill-implement-consumer?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/skill-implement-consumer.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/v4sdk/skill-implement-consumer.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by anishprasad01** [comment]
Hi @ShilpaSharePoint,

I have a couple questions for you.

- When you say you deployed both bots on Azure, what does that mean? The README does not ask you to deploy the bots to Azure, it only asks you to create a registration. What exactly did you do, and how did you configure it?
- When you created your Azure Bot resources, what `AppType` did you choose?
- When the bot failed to operate without filling in `AppType` and `TenantId`, did you try adding those in to see if it worked?

**Comment by ShilpaSharePoint** [comment]
hi @anishprasad01, 

When you say you deployed both bots on Azure, what does that mean?  - Created bot registration as per the readme and published via app service.(last section of the Readme- https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=singletenant%2Cnewgroup%2Ccsharp)
When you created your Azure Bot resources, what AppType did you choose? - **SingleTenant**
When the bot failed to operate without filling in AppType and TenantId, did you try adding those in to see if it worked?- Yes i added AppType and TenantId then Parent bot is working fine, but invoking skill shows error as described:

The method in 'SsoSkillDialog' class throws exception as Object reference not set to an instance of an object.
await userTokenClient.GetUserTokenAsync

Does not get the token
[Error] Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer: Connection ID: An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by anishprasad01** [comment]
Try creating both as `MultiTenant` registrations instead. These offer the broadest compatibility and can help isolate other issues.

**Comment by ShilpaSharePoint** [comment]
Hi  @anishprasad01,

We have requirement of creating bot for organization purpose, need to go with SingleTenant bots only.

**Comment by anishprasad01** [comment]
Then the next step is to check some common pitfalls. It should be noted that the samples and their READMEs were designed for MultiTenant bots. As per the [skills documentation](https://docs.microsoft.com/en-us/azure/bot-service/skill-implement-skill?view=azure-bot-service-4.0&tabs=cs), SingleTenant skills should work as long as the requirements are met.

- Single Tenant bots **must** have both AppType and TenantId filled in.
- Are both bots in the same tenant?
- Is the `Allowed Callers` section correct?

**Comment by ShilpaSharePoint** [comment]
Hi @anishprasad01,
Single Tenant bots must have both AppType and TenantId filled in - **Yes added values for both AppType and TenantId**
Are both bots in the same tenant? - **yes**
Is the Allowed Callers section correct?- **Yes**

**Comment by anishprasad01** [comment]
Thank you. I will attempt to repro.

**Comment by anishprasad01** [comment]
@ShilpaSharePoint,

I set up this sample using two Single Tenant bots in the same tenant following the instructions in the README, and it is working correctly. I was able to sign in to both the root and skill bots and run through the flow without issue.

Thus, there's probably still a misconfiguration somewhere in your bots. Let's check a few more things:

- Did you add the `TenantId` in the SSO configuration?
- Did you add the SSO connection name in both bots?
- Can you confirm the tenant you placed the bots in is the same as the `TenantId` you supplied? It's odd that it's complaining about the "Bot Framework" Tenant.
- Did you update the `Manifest` in the App Registration as per the [documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-sso?view=azure-bot-service-4.0&tabs=csharp%2Ceml#create-the-azure-ad-identity-for-rootbot)?
- In the App Registration under **Authentication**, did you add the **Web** platform with the **Redirect URI** specified in the [document](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=userassigned%2Caadv2%2Ccsharp#create-the-azure-ad-identity-provider)?
- Did you try testing the SSO connections in the Azure Portal to ensure they are working?

The error message suggests that the `TenantId` is the most likely culprit, so we should run through everywhere it appears.

**Comment by ShilpaSharePoint** [comment]
Hi @anishprasad01,

I am able to solve the issue. Issue was SSO connection name, which was having some extra character. Thank you so much for helping me to solve the issue & for quick response.
