### ISSUE TITLE
Middleware Error

### ISSUE THREAD

**Issue by FRANZKAFKA13** [MicrosoftDocs/bot-docs#368]
I get the following error when trying to start the bot:

// Start bot
C:\Users\MYNAME\myJsBots\v4\testbot-v-4&gt;node app.js

// Error

C:\Users\MYNAME\myJsBots\v4\testbot-v-4\node_modules\botbuilder-core\lib\middlewareSet.js:58
                throw new Error(`MiddlewareSet.use(): invalid plugin type being added.`);

Error: MiddlewareSet.use(): invalid plugin type being added.
    at middleware.forEach (C:\Users\MYNAME\myJsBots\v4\testbot-v-4\node_modules\botbuilder-core\lib\middlewareSet.js:58:23)
    at Array.forEach (&lt;anonymous&gt;)
    at MiddlewareSet.use (C:\Users\MYNAME\myJsBots\v4\testbot-v-4\node_modules\botbuilder-core\lib\middlewareSet.js:50:20)
    at BotFrameworkAdapter.use (C:\Users\MYNAME\myJsBots\v4\testbot-v-4\node_modules\botbuilder-core\lib\botAdapter.js:24:53)
    at Object.&lt;anonymous&gt; (C:\Users\MYNAME\myJsBots\v4\testbot-v-4\app.js:18:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

Do you have any solution? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfaad3f2-75c5-e958-4734-8925d03d95c6
* Version Independent ID: 8d98b390-5368-1fa4-8cce-3b0cff252eaa
* Content: [Create a bot using Bot Builder SDK for JavaScript - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/javascript/bot-builder-javascript-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/javascript/bot-builder-javascript-quickstart.md)
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by JonathanFingold** [comment]
@FRANZKAFKA13 , To start the bot, enter `npm start`.

I'll update the instructions to be more clear. You can also get help from our support team. https://stackoverflow.com/questions/tagged/botframework.

**Comment by sateesh1988** [comment]
Hi Team,

we are working on a bot of framework version 4. We need to state the conversation in Azure cosmos DB. We have added botbuilder-azure and ended up with the below issue:-
    at middleware.forEach (c:\Users\kumar.makthala\Downloads\BotBuilder-Samples-master\BotBuilder-Samples-master\samples\javascript_nodejs\25.logger\node_modules\botbuilder-core\lib\middlewareSet.js:58:23)
    at Array.forEach (<anonymous>)
    at MiddlewareSet.use (c:\Users\kumar.makthala\Downloads\BotBuilder-Samples-master\BotBuilder-Samples-master\samples\javascript_nodejs\25.logger\node_modules\botbuilder-core\lib\middlewareSet.js:50:20)
    at BotFrameworkAdapter.use (c:\Users\kumar.makthala\Downloads\BotBuilder-Samples-master\BotBuilder-Samples-master\samples\javascript_nodejs\25.logger\node_modules\botbuilder-core\lib\botAdapter.js:31:53)
    at Object.<anonymous> (c:\Users\kumar.makthala\Downloads\BotBuilder-Samples-master\BotBuilder-Samples-master\samples\javascript_nodejs\25.logger\index.js:111:9)
    at Module._compile (internal/modules/cjs/loader.js:719:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
Waiting for the debugger to disconnect...
Error: MiddlewareSet.use(): invalid plugin type being added.
middlewareSet.ts:106
    at middleware.forEach (c:\Users\kumar.makthala\Downloads\BotBuilder-Samples-master\BotBuilder-Samples-master\samples\javascript_nodejs\25.logger\node_modules\botbuilder-core\src\middlewareSet.ts:106:23)
    at Array.forEach (<anonymous>)
    at MiddlewareSet.use (c:\Users\kumar.makthala\Downloads\BotBuilder-Samples-master\BotBuilder-Samples-master\samples\javascript_nodejs\25.logger\node_modules\botbuilder-core\src\middlewareSet.ts:100:20)
    at BotFrameworkAdapter.use (c:\Users\kumar.makthala\Downloads\BotBuilder-Samples-master\BotBuilder-Samples-master\samples\javascript_nodejs\25.logger\node_modules\botbuilder-core\src\botAdapter.ts:75:37)
    at Object.<anonymous> (c:\Users\kumar.makthala\Downloads\BotBuilder-Samples-master\BotBuilder-Samples-master\samples\javascript_nodejs\25.logger\index.js:111:9)
    at Module._compile (internal/modules/cjs/loader.js:719:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)

I have seen the same issue listed above but the issues was closed. could you please reopen the issue and provide us the solution and its a blocker to us currently. Any alternative solution is appreciated

**Comment by vhbazan** [comment]
Hi guys, 

I am currently following the "[Write directly to storage](https://docs.microsoft.com/en-gb/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=javascript)" guide for azure-bot-service v4.0 and in the section **Using Cosmos DB > Implementation ** when starting the bot (npm start) then I am getting the same error: 

LAMU02X4F9RJG5J:optum-rx-bot-test vbazanm$ npm start

> optum-rx-bot-test@1.0.0 start /Users/vbazanm/www/ms/optum-rx-bot-test
> tsc --build && node ./lib/index.js

/Users/vbazanm/www/ms/optum-rx-bot-test/node_modules/botbuilder-core/lib/middlewareSet.js:58
                throw new Error(`MiddlewareSet.use(): invalid plugin type being added.`);
                ^

Error: MiddlewareSet.use(): invalid plugin type being added.
    at middleware.forEach (/Users/vbazanm/www/ms/optum-rx-bot-test/node_modules/botbuilder-core/lib/middlewareSet.js:58:23)
    at Array.forEach (<anonymous>)
    at MiddlewareSet.use (/Users/vbazanm/www/ms/optum-rx-bot-test/node_modules/botbuilder-core/lib/middlewareSet.js:50:20)
    at BotFrameworkAdapter.use (/Users/vbazanm/www/ms/optum-rx-bot-test/node_modules/botbuilder-core/lib/botAdapter.js:31:53)
    at Object.<anonymous> (/Users/vbazanm/www/ms/optum-rx-bot-test/lib/index.js:74:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! optum-rx-bot-test@1.0.0 start: `tsc --build && node ./lib/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the optum-rx-bot-test@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:



Any idea about this? is the documentation outdated? I am using the typescript version of the sample local bot in this [guide](https://docs.microsoft.com/en-gb/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0)

Many thanks!
